FROM alpine:latest

RUN apk add curl && curl -Lo rancher-cli.tar.gz https://github.com/rancher/cli/releases/download/$VERSION/rancher-linux-amd64-$VERSION.tar.gz
RUN tar zxf rancher-cli.tar.gz && mv rancher-$VERSION/rancher /usr/bin && rm rancher-cli.tar.gz

ENTRYPOINT [ "/usr/bin/rancher" ]

